id: IAA9C309A
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T18:34:01.774332'
last_modified: '2022-05-30T18:34:01.774337'
parser: null
source_metadata:
  title: Chomden Rigpé Raldri
  language: fr
  description: 'Texts by and about Chomden Rigpé Raldri (bcom ldan rig pa''i ral gri,
    1227–1305), a celebrated scholar connected with Narthang Monastery:'
  volume:
    fD748:
      title: Synopsis of the Treasury of Abhidharma (Abhidharmakośa)
      base_file: fD748.txt
      order: 1
      parent: Abhidharma
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
